[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Andreas Timoudas", email = "andreas.timoudas@axenon.se"}]
dynamic = ["version", "description"]
